
SELECT * FROM `heroe`


INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES ('1', 'La ciencia\r\nque esconde la\r\nCatedral de Burgos', 'La unión del arte y la ciencia', 'Durante 800 años, la Catedral de Burgos ha acumulado misterios, saberes y artes en su interior que son muestra de algunos de los avances científicos, técnicos y tecnológicos de diferentes épocas, desde la revolución del gótico hasta las más modernas tecnologías aplicadas a la seguridad y la restauración para mantener el edificio en la mejor de las condiciones.\r\n\r\nEn La Ciencia que esconde la Catedral de Burgos nos adentramos en los secretos de la construcción, decoración, mantenimiento y restauración de uno de los templos más bellos y reconocibles del mundo de la mano de quince especialistas que nos mostrarán cómo las diferentes ciencias y artes se han dado cita en el interior y exterior de la seo burgalesa, quince expertos que nos guiarán en este viaje gracias a sus conocimientos en matemáticas, física, química, his[...]','');

INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES (NULL, 'Capítulos', 'Ocho episodios para conocer la catedral', '¿Qué hace grandiosa a una catedral? ¿Por qué la de Burgos es única? ¿Qué convierte a una acumulación de piedras y maderas labradas en una obra de arte de fama mundial? Detrás de la construcción, de la mística y la restauración se encuentran multitud de aspectos científicos, técnicos y tecnológicos presentes en cada rincón.\r\n\r\nEn los ocho episodios que componen la serie La ciencia que esconde la Catedral de Burgos recorreremos cada uno de los aspectos más importantes para la construcción, mantenimiento y conservación de la seo burgalesa, pero también en aquellos aspectos artísticos singulares que la convierten en una de las joyas del gótico y uno de los edificios más singulares del mundo.', '');
                                                                          
INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES (NULL, 'Expertos', 'Los mejores guías', 'Quince expertos nos acompañan en la aventura de descubrir los misterios científicos y tecnológicos de la Catedral de Burgos. Profesores universitarios, profesionales de enorme prestigio, restauradoras, artesanos e, incluso, el archivero de la propia Catedral serán nuestros guías, aunandoun gran nivel de conocimientos con un lenguaje sencillo y para todos los públicos.\r\n\r\nEn los ocho episodios que conforman la serie, las entrevistas a los especialistas nos sirven tanto de hilo conductor como de fuente de conocimientos y explicaciones de materias tan diferentes como la arquitectura, los materiales, las vidrieras, las matemáticas presentes en el diseño y la decoración, la música, las más modernas tecnologías o el estado de conservación y futuro de la Catedral de Burgos. Un reparto de lujo para conocer al detalle la ciencia y la tecnología presentes en cada rincón del templo', '');

INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES (NULL, 'El proyecto', 'Conocimiento científico en el arte y el patrimonio.', 'La ciencia que esconde la Catedral de Burgos es una serie documental que nos adentra en el conocimiento científico, técnico y tecnológico empleado en la construcción, mantenimiento y restauración de la catedral de Burgos. Su estreno coincide con el octavo centenario de la colocación de la primera piedra del monumento burgalés y celebra la existencia del templo como compendio de todas las ciencias y artes que, con el paso de los siglos, se han puesto al servicio del edificio.\r\nEl objetivo de la serie es acercar a la ciudadanía la grandeza de la Catedral de Burgos, más allá de su aspecto religioso, para ayudar a comprender la importancia del conocimiento científico en el arte y el patrimonio.\r\n\r\nLa serie ha sido producida por la Unidad de Cultura Científica de la Universidad de Burgos (UCC+i) con la colaboración de la Fundación Española para la Ciencia y la Tecnología – Ministerio de Ciencia e Innovación y el Cabildo Metropolitano de la Catedral de Burgos.', '');

INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES (NULL, 'Créditos y reconocimiento', 'La divulgación científica de la Catedral de Burgos', 'En este proyecto han participado varias instituciones, asociaciones, individuos y creativos….', '');

INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES (NULL, 'DOCUMENTACIÓN GRÁFICA', 'Fotos, ilustraciones, documentos,  planos y vídeos', 'Se realizó una profunda búsqueda de documentos, ilustraciones, fotos, planos y vídeos que consiguieran explicar los hitos del documental. A continuación se pueden ver algunos de los encontrados en los fondos y archivos documentales públicos.\r\n\r\nTodos están referenciados, el título enlaza con la institución correspondiente y propietaria. De esta manera más personas podrán disfrutar de los documentos.', '');

INSERT INTO `heroe` (`id`, `Titulo`, `subtitulo`, `texto`, `img`) VALUES (NULL, 'Bibliografía', 'Los libros, guardianes del conocimiento científico', 'La documentación y obtención de conocimiento es fundamental para hablar de los aspectos científicos que aparecen en La Catedral de Burgos. Se realizó una amplia lectura y entre estas destacamos cuales fueron las principales fuentes de información. También añadimos un libro publicado por la Universidad de Burgos con todas las actuaciones entorno a la catedral.', '');