INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo I', 'La arquitectura', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-La-arquitectura-min.jpg', '', 'Nos acercaremos a los orígenes de la Catedral de Burgos, sus momentos clave, su milenario archivo y la revolución del gótico. Los historiadores René Payo y José Matesanz sitúan los hitos más importantes de su construcción. El archivero Matías Vicario abre las puertas del Archivo, la memoria del edificio y fuente de información para los investigadores. Jesús Garabito, actual arquitecto de la catedral, explica las peculiaridades de su emplazamiento y la revolución del gótico.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo II', 'La piedra', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-La-piedra-min.jpg', '', 'En este capítulo conoceremos el origen de la piedra que conforma la Catedral, sus propiedades, la forma de trabajarla y su restauración. Gabriel García, gestor de las canteras de Hontoria-Cubillo, explica la extracción de la piedra y su transporte con carreteros. Por su parte, José Javier Barrio  escultor y restaurador, presenta las claves del cuidado y la restauración de la piedra, incluyendo sus volúmenes y su característico color blanco, desvelado, para sorpresa de la ciudadanía, tras una larga limpieza integral.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo III', 'Las matemáticas', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-Las-matematicas-min.jpg', '', 'Conoceremos proporciones y formas escondidas en la Catedral de Burgos, como la vesica piscis, la proporción áurea, el número de plata y el número cordobés. Los historiadores René Payo y José Matesanz introducen la relevancia de la geometría para los constructores medievales y posteriores. El matemático Constantino de la Fuente desgrana algunas de las proporciones más importantes presentes en el templo, relacionadas con números irracionales.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo IV', 'La pintura', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-La-pintura-min.jpg', '', 'Presentamos el uso de la química y otras herramientas para limpiar y recuperar los colores y las policromías de los cuadros, las estatuas y los retablos. Francisco del Hoyo, pintor y restaurador, explica cómo abordan su trabajo en su profesión, analizando, documentando y actuando sobre la pintura antigua y las capas de alteración. Las restauradoras Mercedes Chico e Itsaso Artexe abren su taller para contar cómo abordar la limpieza y conservación sobre madera y arte mueble.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo V', 'Las vidrieras', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-Las-vidrieras-min.jpg', '', 'Estudiamos la luz mediante técnicas y materiales para crear vidrio, pintar y componer vidrieras, así como las investigaciones modernas sobre las vidrieras, en las que se ha encontrado un nuevo pigmento denominado «rojo Burgos«. La historiadora del arte Pilar Alonso expone las características, composición, historia y estudio de las vidrieras.  Enrique Barrio, pintor y vidriero, muestra cómo realiza vidrieras en su taller, empleando muchas técnicas similares a los artesanos y artistas del pasado.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo VI', 'La música', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-La-musica-min.jpg', '', 'Repasamos la historia y las propiedades de los órganos, así como la composición y el mantenimiento de las campanas de la Catedral de Burgos. El restaurador de órganos Óscar Laguna cuenta las características físicas que hacen idóneo este instrumento en las catedrales, además de mostrar su funcionamiento, su interior y su reparación. El campanero Antonio Cano presenta las campanas de la catedral y su fabricación.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo VII', 'Las tecnologías modernas', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-Las-tecnologias-modernas-min.jpg', '', 'Conoceremos la historia del reloj y el Papamoscas de la Catedral de Burgos, así como sus sistemas actuales de calefacción, iluminación y seguridad. Antonio Cano, campanero y relojero, explica el funcionamiento del famoso autómata Papamoscas y su automatización moderna, como la de las campanas. El arquitecto técnico y restaurador Miguel Ángel Ortega muestra los sistemas y los retos de la calefacción, la iluminación, los pararrayos y la seguridad antiincendios.');

INSERT INTO `capitulos` (`id`, `Titulo`, `subtitulo`, `img`, `video`, `texto`) VALUES (NULL, 'Capítulo VIII', 'La conservación', 'https://cienciaycatedral.ubuinvestiga.es/wp-content/uploads/sites/14/2022/06/La-ciencia-que-esconde-la-catedral-de-Burgos-La-conservacion-min.jpg', '', 'Resumimos las restauraciones de las décadas posteriores a la caída y destrucción de la estatua de San Lorenzo, en 1994. El historiador René Payo y el arquitecto Javier Garabito hacen balance de las actuaciones realizadas durante estos años en la Catedral de Burgos hasta su pulcro estado en la celebración de su VIII Centenario. La serie finaliza con reflexiones sobre el futuro de la Catedral y el papel de la ciencia y la tecnología en su creación y conservación.');